module Seed
  Skill.create([
    {id: 1, name: "Basics 1", active: true},
    {id: 2, name: "Dates", active: false},
    {id: 3, name: "Work", active: false},
    {id: 4, name: "Verb infinitive", active: false},
    {id: 5, name: "Adessive case", active: false},
    {id: 6, name: "Ablative case", active: false},
    {id: 7, name: "Allative case", active: false},
    {id: 8, name: "Adverbs", active: false},
    {id: 9, name: "Places", active: false},
    {id: 10, name: "Essive case", active: false},
    {id: 11, name: "Translative case", active: false},
    {id: 12, name: "Instructive case", active: false},
    {id: 13, name: "Abessive case", active: false},
    {id: 14, name: "Commitative case", active: false},
    {id: 15, name: "Objects", active: false},
    {id: 16, name: "Clothes", active: false},
    {id: 17, name: "Adjectives", active: false},
    {id: 18, name: "Negations", active: false},
    {id: 19, name: "Conjunctions", active: false},
    {id: 20, name: "Pronouns", active: false},
    {id: 21, name: "Prepositions", active: false},
    {id: 22, name: "Verb past", active: false},
    {id: 23, name: "Travel", active: false},
    {id: 24, name: "Pronouns 2", active: false},
    {id: 25, name: "Abstract", active: false},
    {id: 26, name: "Verb imperative", active: false},
    {id: 27, name: "Indefinite pronouns", active: false},
    {id: 28, name: "Reflexive pronouns", active: false},
    {id: 29, name: "Demonstrative pronouns", active: false},
    {id: 30, name: "Relative pronouns", active: false},
    {id: 31, name: "Personal pronouns", active: false},
    {id: 32, name: "Interrogative pronouns", active: false},
    {id: 33, name: "Irregular pronouns", active: false},
    {id: 34, name: "Morphemes (prefix, suffix, etc)", active: false},
    {id: 35, name: "Nouns", active: false},
    {id: 36, name: "Postpositions", active: false},
    {id: 37, name: "Colors", active: false}
  ])
end